export const payload = {

    templates:
        [
            {
                "id":1,
                "name": "Change of address",
                "description": "Please provide all required informations",
                "attributes": "[{\"type\":\"text\",\"order\":\"1\",\"name\":\"Building Number\",\"description\":\"please enter Building Number\",\"required\":true,\"defaultValue\":\"\"},{\"type\":\"textarea\",\"order\":1,\"name\":\"Street name\",\"description\":\"Please enter Street name\",\"required\":true},{\"type\":\"text\",\"order\":2,\"name\":\"Address\",\"description\":\"please enter full address\",\"required\":true},{\"type\":\"text\",\"order\":3,\"name\":\"City\",\"description\":\"please enter city\",\"required\":true},{\"type\":\"select\",\"order\":4,\"name\":\"State\",\"description\":\"please choose state\",\"options\":[\"Alabama\",\"Texas\",\"Arizona\",\"washington\"],\"required\":true,\"defaultValue\":\"Texas\"},{\"type\":\"date\",\"order\":5,\"name\":\"Address changed \",\"description\":\"please choose the date you chagned the address\",\"options\":\"date\",\"required\":true,\"defaultValue\":\"-7 days\"},{\"type\":\"textarea\",\"order\":6,\"name\":\"Notes\",\"description\":\"please add any notes or comments\",\"rows\":3}]"
            },
            {
                "id":2,
                "name": "Insurance Renewal",
                "description": "Please provide all required informations",
                "attributes": "[{\"type\":\"text\",\"order\":\"1\",\"name\":\"Building Number\",\"description\":\"please enter Building Number\",\"required\":true,\"defaultValue\":\"\"},{\"type\":\"textarea\",\"order\":1,\"name\":\"Street name\",\"description\":\"Please enter Street name\",\"required\":true},{\"type\":\"text\",\"order\":2,\"name\":\"Address\",\"description\":\"please enter full address\",\"required\":true},{\"type\":\"text\",\"order\":3,\"name\":\"City\",\"description\":\"please enter city\",\"required\":true},{\"type\":\"select\",\"order\":4,\"name\":\"State\",\"description\":\"please choose state\",\"options\":[\"Alabama\",\"Texas\",\"Arizona\",\"washington\"],\"required\":true,\"defaultValue\":\"Texas\"},{\"type\":\"date\",\"order\":5,\"name\":\"Address changed \",\"description\":\"please choose the date you chagned the address\",\"options\":\"date\",\"required\":true,\"defaultValue\":\"-7 days\"},{\"type\":\"textarea\",\"order\":6,\"name\":\"Notes\",\"description\":\"please add any notes or comments\",\"rows\":3}]"
            }
        ],
    regions: [{ "label": "US East (Ohio)", "value": "us-east-2" }, { "label": "US East (N. Virginia)", "value": "us-east-1" }, { "label": "US West (N. California)", "value": "us-west-1" }, { "label": "US West (Oregon)", "value": "us-west-2" }, { "label": "Africa (Cape Town)", "value": "af-south-1" }, { "label": "Asia Pacific (Hong Kong)", "value": "ap-east-1" }, { "label": "Asia Pacific (Jakarta)", "value": "ap-southeast-3" }, { "label": "Asia Pacific (Mumbai)", "value": "ap-south-1" }, { "label": "Asia Pacific (Osaka)", "value": "ap-northeast-3" }, { "label": "Asia Pacific (Seoul)", "value": "ap-northeast-2" }, { "label": "Asia Pacific (Singapore)", "value": "ap-southeast-1" }, { "label": "Asia Pacific (Sydney)", "value": "ap-southeast-2" }, { "label": "Asia Pacific (Tokyo)", "value": "ap-northeast-1" }, { "label": "Canada (Central)", "value": "ca-central-1" }, { "label": "Europe (Frankfurt)", "value": "eu-central-1" }, { "label": "Europe (Ireland)", "value": "eu-west-1" }, { "label": "Europe (London)", "value": "eu-west-2" }, { "label": "Europe (Milan)", "value": "eu-south-1" }, { "label": "Europe (Paris)", "value": "eu-west-3" }, { "label": "Europe (Stockholm)", "value": "eu-north-1" }, { "label": "Middle East (Bahrain)", "value": "me-south-1" }, { "label": "Middle East (UAE)", "value": "me-central-1" }, { "label": "South America (São Paulo)", "value": "sa-east-1" }, { "label": "AWS GovCloud (US-East)", "value": "us-gov-east-1" }, { "label": "AWS GovCloud (US-West)", "value": "us-gov-west-1" }]

}